apiVersion: batch/v1
kind: CronJob
metadata:
  name: limitwarden
spec:
  schedule: "0 * * * *"  # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: limitwarden-sa
          containers:
          - name: limitwarden
            image: marienginx/limitwarden:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: "100m"
                memory: "128Mi"
              limits:
                cpu: "200m"
                memory: "256Mi"
          restartPolicy: OnFailure
