image:
  repository: marienginx/limitwarden
  tag: latest
  pullPolicy: Always

schedule: "0 * * * *"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"
